enum e_OffsetTypes {
    VEHICLE_OFFSET_BOOT,
    VEHICLE_OFFSET_HOOD,
    VEHICLE_OFFSET_ROOF
};
enum purchaseList {
	PURCHASE_NONE,
	PURCHASE_CARSLOT,
	PURCHASE_VIP,
	PURCHASE_UNBAN,
	PURCHASE_UNJAIL,
	PURCHASE_IST,
	PURCHASE_TEISES,
	PURCHASE_SPAZ,
	PURCHASE_GESINTUVAS,
	PURCHASE_FIX,
	PURCHASE_SOTUMAS,
	PURCHASE_SKIN,
	PURCHASE_LOTO,
	PURCHASE_SPALVA,
	PURCHASE_STILIUS,
	PURCHASE_NUMERIAI,
	PURCHASE_VARDAS
}

enum 
{
	PAN_AKAUNTAS,
	PAN_INVENTORIUS,
	PAN_VEIKSMAI,
	PAN_APANELE,
	PAN_NUSTATYMAI,
	PAN_STILIAI,
	PAN_KOVOS,
	PAN_KREDITAI,
	PAN_ATASKAITOS,
	PAN_ELPASTAS,
	PAN_ELITINIAI
}
enum
{
	INV_TELEFONAS,
	INV_MONEY,
	INV_KREDITINE,
	INV_NARK,
	INV_ZOLE,
	INV_SEKLOS,
	INV_GUN,
	INV_GERIMAS,
	INV_RAKTAS, 
	INV_TEISES,
	INV_TEISESM,
	INV_TEISESS,
	INV_SPAZ,
	INV_AKINIAI,
	INV_ZUVIS,
	INV_MASALAS,
	INV_BAKELIS,
	INV_MAISTAS,
	INV_MAISTASLAUK,
	INV_LSD,
	INV_ADR,
	INV_LAIKRODIS,
	INV_RATAI,
	INV_KEPURE,
	INV_SALMAS,
	INV_RUBAI,
	INV_SPALVOS,
	INV_CIGARETES,
	INV_TAZERIS,
	INV_LAISKAI,
	INV_DOVANA
} 
enum
{
	PLACE_NONE,
	PLACE_PLANE,
	PLACE_HOUSE,
	PLACE_BIZ,
	PLACE_GARAGE,
	PLACE_BASEINAS,
	PLACE_DAUGIABUTIS,
	PLACE_SRATASVYDIS,
	PLACE_DUEL,
	PLACE_VMTEST,
	PLACE_FULE, 
	PLACE_WORLD
}

enum {
    CommonRed = 19006,
    CommonOrange,
    CommonGreen,
    CommonBlue,
    CommonPurple,
    CommonEspiral,
    CommonBlack,
    CommonEyes,
    CommonXadrex,
    CommonTransparent,
    CommonXRayVision,
    SquareFormatYellow,
    SquareFormatOrange,
    SquareFormatRed,
    SquareFormatBlue,
    SquareFormatGreen,
    RayBanGray,
    RayBanBlue,
    RayBanPurple,
    RayBanPink,
    RayBanRed,
    RayBanOrange,
    RayBanYellow,
    RayBanGreen,
    CircularNormal,
    CircularYellow,
    CircularRed,
    CircularBlack,
    CircularXadrex,
    CircularThunders,
    CopGlassesBlack = 19138,
    CopGlassesRed = 19139,
    CopGlassesBlue = 19140,
};






